### ISSUE TITLE
The post layout and detail are not following the design

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/mooncake#27]
## Generic information
- OS name and version: iOS 13.5
- Application build code: 4004
- Network type (mobile/Wi-Fi):  Wi-Fi

## Bug description

- [x] The post of margin on the 4 sides are equal. (`8px`) - 1
- [x] The profile icon should be bigger (`40px`) - 2
- [x] Change the font of the user name to SF Pro Text Medium, 16px `#000000` - 3
- [x] Change the font of the time to SF Pro Text Regular, 12px `#646464` - 4 
- [ ] Change  the background colour of reactions to `#F4F4FC` - 5
- [x] Change the colour of the number next to the 3 icons to `#6D4DDB` - 6
- [x] Change the "dot" colour to `#6D4DDB` or  `#6D4DDB 15% transparency` - 7
- [ ] Change the "more icon" colour to `#999999` - 8
- [ ] The spacing between the 3 icons (like, comment, reaction) should be always equal (`20 px`), - 9
- [x] Change the order of icons - 10

## Expected behavior
https://xd.adobe.com/view/a017302b-fd5d-4ad5-481b-19968582ae5f-d626/screen/f991f826-117b-4894-b5dd-080d0af9c23a/3-0-post/

![post details](https://user-images.githubusercontent.com/932636/83608892-0d0cef00-a5b0-11ea-95ed-220ef0d11357.png)

**Comment by ryuash** [comment]
@kwunyeung 
Need more context on **5** and **8** I have no idea what you're talking about.
**6** - I updated but this doesn't even follow the given wireframe
**9** - I don't think this requirement is realistic especially if I have a small iphone 5s. Currently we're using space-evenly
